#!/bin/bash

dell ()    {

	IFS='/' read -ra my_array <<< "$1"

	local num1="${my_array[0]}"

	local num2="${my_array[1]}"

	if [ $num2 != 0 ]; then

		local division=$(echo "20k $num1 $num2 / p" | dc )

		echo $division

		exit 0

	else

		echo "You try divide by zero"

		exit 128

	fi


}
